name: analyseur_live_flutter_5octobre
description: A new Flutter project.

# Ce fichier permet d'indiquer les packages qu'on installe
# permet aussi d'incorporer des polices de caracteres au projet
# permet aussi d'incorporer des images dans notre projet


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
# on pourra rajouter des extensions 
# une extension pour faire des requêtes réseaux
# une entension pour jouer un son 
# ...... 
# faire attention au tabulation 


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Partie pour rajouter des images 
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # section ou on indique à flutter ou se trouve notre police de caractères
  # example:
  fonts:
  # un tab + un tiret + un espace + family: Pacifico
    - family: Pacifico
      fonts:
        # Deux espaces , on aligne le tiret sur le n de fonts
        - asset: fonts/Pacifico-Regular.ttf

  # quand on sauvegarde le fichier - flutter pub get 
  
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
